CREATE TABLE IF NOT EXISTS "rankProgress" ("_id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, "personaId" INTEGER NOT NULL, "rankTitle" TEXT NOT NULL, "currentRankScore" INTEGER NOT NULL, "nextRankScore" INTEGER NOT NULL, "currentScore" INTEGER NOT NULL);

