package com.ninetwozero.bf3droid.util;

import java.util.HashMap;
import java.util.Map;

public class AwardsMap {

    private AwardsMap(){}

    private static Map<String, String> AWARDS = new HashMap<String, String>(){{
        put("BF3_ID_P_AWARD_M01_NAME", "Assault Rifle Medal");
        put("BF3_ID_P_AWARD_M02_NAME", "Carbine Medal");
        put("BF3_ID_P_AWARD_M03_NAME", "Light Machine Gun Medal");
        put("BF3_ID_P_AWARD_M04_NAME", "Sniper Rifle Medal");
        put("BF3_ID_P_AWARD_M05_NAME", "Handgun Medal");
        put("BF3_ID_P_AWARD_M06_NAME", "Shotgun Medal");
        put("BF3_ID_P_AWARD_M07_NAME", "Pdw Medal");
        put("BF3_ID_P_AWARD_M08_NAME", "Melee Medal");
        put("BF3_ID_P_AWARD_M09_NAME", "Anti Vehicle Medal");
        put("BF3_ID_P_AWARD_M10_NAME", "Accuracy Medal");
        put("BF3_ID_P_AWARD_M11_NAME", "Avenger Medal");
        put("BF3_ID_P_AWARD_M12_NAME", "Savior Medal");
        put("BF3_ID_P_AWARD_M13_NAME", "Nemesis Medal");
        put("BF3_ID_P_AWARD_M14_NAME", "Suppression Medal");
        put("BF3_ID_P_AWARD_M15_NAME", "Mvp Medal");
        put("BF3_ID_P_AWARD_M16_NAME", "2nd Mvp Medal");
        put("BF3_ID_P_AWARD_M17_NAME", "3rd Mvp Medal");
        put("BF3_ID_P_AWARD_M18_NAME", "Ace Squad Medal");
        put("BF3_ID_P_AWARD_M19_NAME", "Combat Efficiency Medal");
        put("BF3_ID_P_AWARD_M20_NAME", "Transport Warfare Medal");
        put("BF3_ID_P_AWARD_M21_NAME", "Armored Warfare Medal");
        put("BF3_ID_P_AWARD_M22_NAME", "Air Warfare Medal");
        put("BF3_ID_P_AWARD_M23_NAME", "Stationary Emplacement Medal");
        put("BF3_ID_P_AWARD_M24_NAME", "M-com Attacker Medal");
        put("BF3_ID_P_AWARD_M25_NAME", "M-com Defender Medal");
        put("BF3_ID_P_AWARD_M26_NAME", "Rush Medal");
        put("BF3_ID_P_AWARD_M27_NAME", "Conquest Medal");
        put("BF3_ID_P_AWARD_M28_NAME", "Team Deathmatch Medal");
        put("BF3_ID_P_AWARD_M29_NAME", "Squad Rush Medal");
        put("BF3_ID_P_AWARD_M30_NAME", "Squad Deathmatch Medal");
        put("BF3_ID_P_AWARD_M31_NAME", "Flag Attacker Medal");
        put("BF3_ID_P_AWARD_M32_NAME", "Flag Defender Medal");
        put("BF3_ID_P_AWARD_M33_NAME", "Resupply Medal");
        put("BF3_ID_P_AWARD_M34_NAME", "Maintenance Medal");
        put("BF3_ID_P_AWARD_M35_NAME", "Medical Medal");
        put("BF3_ID_P_AWARD_M36_NAME", "Surveillance Medal");
        put("BF3_ID_P_AWARD_M37_NAME", "Mortar Medal");
        put("BF3_ID_P_AWARD_M38_NAME", "Laser Designator Medal");
        put("BF3_ID_P_AWARD_M39_NAME", "M18 Claymore Medal");
        put("BF3_ID_P_AWARD_M40_NAME", "Radio Beacon Medal");
        put("BF3_ID_P_AWARD_M41_NAME", "Us Marines Service Medal");
        put("BF3_ID_P_AWARD_M42_NAME", "Ru Army Service Medal");
        put("BF3_ID_P_AWARD_M43_NAME", "Assault Service Medal");
        put("BF3_ID_P_AWARD_M44_NAME", "Engineer Service Medal");
        put("BF3_ID_P_AWARD_M45_NAME", "Support Service Medal");
        put("BF3_ID_P_AWARD_M46_NAME", "Recon Service Medal");
        put("BF3_ID_P_AWARD_M47_NAME", "Tank Service Medal");
        put("BF3_ID_P_AWARD_M48_NAME", "Helicopter Service Medal");
        put("BF3_ID_P_AWARD_M49_NAME", "Jet Service Medal");
        put("BF3_ID_P_AWARD_M50_NAME", "Stationary Service Medal");
        put("BF3_ID_P_AWARD_M51_NAME", "TDMCQ Medal");
        put("BF3_ID_P_AWARD_M52_NAME", "Tank Superiority Medal");
        put("BF3_ID_P_AWARD_M53_NAME", "Scanger Medal");
        put("BF3_ID_P_AWARD_M54_NAME", "Domination Medal");
        put("BF3_ID_P_AWARD_M55_NAME", "Gun Master Medal");

        put("BF3_ID_P_AWARD_R01_NAME", "Assault Rifle Ribbon");
        put("BF3_ID_P_AWARD_R02_NAME", "Carbine Ribbon");
        put("BF3_ID_P_AWARD_R03_NAME", "Light Machine Gun Ribbon");
        put("BF3_ID_P_AWARD_R04_NAME", "Sniper Rifle Ribbon");
        put("BF3_ID_P_AWARD_R05_NAME", "Hand Gun Ribbon");
        put("BF3_ID_P_AWARD_R06_NAME", "Shotgun Ribbon");
        put("BF3_ID_P_AWARD_R07_NAME", "Pdw Ribbon");
        put("BF3_ID_P_AWARD_R08_NAME", "Melee Ribbon");
        put("BF3_ID_P_AWARD_R09_NAME", "Disable Vehicle Ribbon");
        put("BF3_ID_P_AWARD_R10_NAME", "Anti Vehicle Ribbon");
        put("BF3_ID_P_AWARD_R11_NAME", "Accuracy Ribbon");
        put("BF3_ID_P_AWARD_R12_NAME", "Avenger Ribbon");
        put("BF3_ID_P_AWARD_R13_NAME", "Savior Ribbon");
        put("BF3_ID_P_AWARD_R14_NAME", "Nemesis Ribbon");
        put("BF3_ID_P_AWARD_R15_NAME", "Suppression Ribbon");
        put("BF3_ID_P_AWARD_R16_NAME", "Mvp Ribbon");
        put("BF3_ID_P_AWARD_R17_NAME", "Mvp 2 Ribbon");
        put("BF3_ID_P_AWARD_R18_NAME", "Mvp 3 Ribbon");
        put("BF3_ID_P_AWARD_R19_NAME", "Ace Squad Ribbon");
        put("BF3_ID_P_AWARD_R20_NAME", "Combat Efficiency Ribbon");
        put("BF3_ID_P_AWARD_R21_NAME", "Anti Explosives Ribbon");
        put("BF3_ID_P_AWARD_R22_NAME", "Squad Spawn Ribbon");
        put("BF3_ID_P_AWARD_R23_NAME", "Squad Wipe Ribbon");
        put("BF3_ID_P_AWARD_R24_NAME", "Transport Warfare Ribbon");
        put("BF3_ID_P_AWARD_R25_NAME", "Armored Warfare Ribbon");
        put("BF3_ID_P_AWARD_R26_NAME", "Stationary Emplacement Ribbon");
        put("BF3_ID_P_AWARD_R27_NAME", "Air Warfare Ribbon");
        put("BF3_ID_P_AWARD_R28_NAME", "M-com Attacker Ribbon");
        put("BF3_ID_P_AWARD_R29_NAME", "M-com Defender Ribbon");
        put("BF3_ID_P_AWARD_R30_NAME", "Rush Winner Ribbon");
        put("BF3_ID_P_AWARD_R31_NAME", "Conquest Winner Ribbon");
        put("BF3_ID_P_AWARD_R32_NAME", "Tdm Winner Ribbon");
        put("BF3_ID_P_AWARD_R33_NAME", "Squad Rush Winner Ribbon");
        put("BF3_ID_P_AWARD_R34_NAME", "Squad Deathmatch Winner Ribbon");
        put("BF3_ID_P_AWARD_R35_NAME", "Rush Ribbon");
        put("BF3_ID_P_AWARD_R36_NAME", "Conquest Ribbon");
        put("BF3_ID_P_AWARD_R37_NAME", "Team Deathmatch Ribbon");
        put("BF3_ID_P_AWARD_R38_NAME", "Squad Rush Ribbon");
        put("BF3_ID_P_AWARD_R39_NAME", "Squad Deathmatch Ribbon");
        put("BF3_ID_P_AWARD_R40_NAME", "Flag Attacker Ribbon");
        put("BF3_ID_P_AWARD_R41_NAME", "Flag Defender Ribbon");
        put("BF3_ID_P_AWARD_R42_NAME", "Resupply Efficiency Ribbon");
        put("BF3_ID_P_AWARD_R43_NAME", "Maintenance Efficiency Ribbon");
        put("BF3_ID_P_AWARD_R44_NAME", "Medical Efficiency Ribbon");
        put("BF3_ID_P_AWARD_R45_NAME", "Surveillance Efficiency Ribbon");
        put("BF3_ID_P_AWARD_R46_NAME", "TDMCQ Winner Ribbon");
        put("BF3_ID_P_AWARD_R47_NAME", "Tank Superiority Winner Ribbon");
        put("BF3_ID_P_AWARD_R48_NAME", "Domination Ribbon");
        put("BF3_ID_P_AWARD_R49_NAME", "Gun Master Ribbon");
        put("BF3_ID_P_AWARD_R50_NAME", "Scavenger Ribbon");
        put("BF3_ID_P_AWARD_R51_NAME", "TDMCQ Ribbon");
        put("BF3_ID_P_AWARD_R52_NAME", "Tank Superiority Ribbon");
        put("BF3_ID_P_AWARD_R53_NAME", "Scavenger Winner Ribbon");
        put("BF3_ID_P_AWARD_R54_NAME", "Domination Winner Ribbon");
        put("BF3_ID_P_AWARD_R55_NAME", "Gun MAster Winner Ribbon");

        put("BF3_ID_P_WSTAR_NAME_M39", "M39 Emr Service Star");
        put("BF3_ID_P_WSTAR_NAME_M60", "M60e4 Service Star");
        put("BF3_ID_P_WSTAR_NAME_M27", "M27 Iar Service Star");
        put("BF3_ID_P_WSTAR_NAME_M26", "M26 Mass Service Star");
        put("BF3_ID_P_WSTAR_NAME_AN94", "An-94 Service Star");
        put("BF3_ID_P_WSTAR_NAME_JACKH", "Mk3a1 Service Star");
        put("BF3_ID_P_WSTAR_NAME_KNIFE", "Knife Service Star");
        put("BF3_ID_P_WSTAR_NAME_M1911SILENCED", "M1911 Supp");
        put("BF3_ID_P_WSTAR_NAME_DAO12", "Dao-12 Service Star");
        put("BF3_ID_P_WSTAR_NAME_G3A4", "G3a3 Service Star");
        put("BF3_ID_P_WSTAR_NAME_G36C", "G36c Service Star");
        put("BF3_ID_P_WSTAR_NAME_PP19", "Pp-19 Service Star");
        put("BF3_ID_P_WSTAR_NAME_L96", "L96 Service Star");
        put("BF3_ID_P_WSTAR_NAME_QBU88", "Qbu-88 Service Star");
        put("BF3_ID_P_WSTAR_NAME_PP2000", "Pp-2000 Service Star");
        put("BF3_ID_P_WSTAR_NAME_F2000", "F2000 Service Star");
        put("BF3_ID_P_WSTAR_NAME_M1911", "M1911 Service Star");
        put("BF3_ID_P_WSTAR_NAME_MP7", "Mp7 Service Star");
        put("BF3_ID_P_WSTAR_NAME_SV98", "Sv98 Service Star");
        put("BF3_ID_P_WSTAR_NAME_M9SILENCED", "M9 Supp");
        put("BF3_ID_P_WSTAR_NAME_MP443SILENCED", "Mp443 Supp");
        put("BF3_ID_P_WSTAR_NAME_RPG7", "Rpg-7v2 Service Star");
        put("BF3_ID_P_WSTAR_NAME_M1911TACTICAL", "M1911 S-tac Service Star");
        put("BF3_ID_P_WSTAR_NAME_M16A4", "M16 Service Star");
        put("BF3_ID_P_WSTAR_NAME_QBB95", "Qbb-95 Service Star");
        put("BF3_ID_P_WSTAR_NAME_GLOCK18SILENCED", "G18 Supp");
        put("BF3_ID_P_WSTAR_NAME_M9", "M9 Service Star");
        put("BF3_ID_P_WSTAR_NAME_FAMAS", "Famas Service Star");
        put("BF3_ID_P_WSTAR_NAME_PECHENEG", "Pkp Pecheneg Service Star");
        put("BF3_ID_P_WSTAR_NAME_C4", "C4 Service Star");
        put("BF3_ID_P_WSTAR_NAME_M240", "M240b Service Star");
        put("BF3_ID_P_WSTAR_NAME_M249", "M249 Service Star");
        put("BF3_ID_P_WSTAR_NAME_M26FRAG", "M26 Frag Service Star");
        put("BF3_ID_P_WSTAR_NAME_QBZ95B", "Qbz-95b Service Star");
        put("BF3_ID_P_WSTAR_NAME_USAS12", "Usas-12 Service Star");
        put("BF3_ID_P_WSTAR_NAME_GLOCK17SILENCED", "G17c Supp");
        put("BF3_ID_P_WSTAR_NAME_870", "870mcs Service Star");
        put("BF3_ID_P_WSTAR_NAME_M416", "M416 Service Star");
        put("BF3_ID_P_WSTAR_NAME_HK53", "Hk53 Service Star");
        put("BF3_ID_P_WSTAR_NAME_M4A1", "M4a1 Service Star");
        put("BF3_ID_P_WSTAR_NAME_MP443", "Mp443 Service Star");
        put("BF3_ID_P_WSTAR_NAME_MP443LIT", "Mp443 Tact");
        put("BF3_ID_P_WSTAR_NAME_AK74M", "Ak-74m Service Star");
        put("BF3_ID_P_WSTAR_NAME_ASVAL", "As Val Service Star");
        put("BF3_ID_P_WSTAR_NAME_IGLA", "Sa-18 Igla Service Star");
        put("BF3_ID_P_WSTAR_NAME_UMP", "Ump-45 Service Star");
        put("BF3_ID_P_WSTAR_NAME_SMAW", "Smaw Service Star");
        put("BF3_ID_P_WSTAR_NAME_SKS", "Sks Service Star");
        put("BF3_ID_P_WSTAR_NAME_MINE", "M15 Mine Service Star");
        put("BF3_ID_P_WSTAR_NAME_SVD", "Svd Service Star");
        put("BF3_ID_P_WSTAR_NAME_SG553", "Sg553 Service Star");
        put("BF3_ID_P_WSTAR_NAME_GLOCK18", "G18 Service Star");
        put("BF3_ID_P_WSTAR_NAME_GLOCK17", "G17c Service Star");
        put("BF3_ID_P_WSTAR_NAME_M1014", "M1014 Service Star");
        put("BF3_ID_P_WSTAR_NAME_M320SG", "M320 Shotgun Service Star");
        put("BF3_ID_P_WSTAR_NAME_L85A2", "L85a2 Service Star");
        put("BF3_ID_P_WSTAR_NAME_M412REX", "M412 Rex Service Star");
        put("BF3_ID_P_WSTAR_NAME_JAVELIN", "Fgm-148 Javelin Service Star");
        put("BF3_ID_P_WSTAR_NAME_M26FLECHETTE", "M26 Dart Service Star");
        put("BF3_ID_P_WSTAR_NAME_AKS74U", "Aks-74u Service Star");
        put("BF3_ID_P_WSTAR_NAME_MG36", "Mg36 Service Star");
        put("BF3_ID_P_WSTAR_NAME_KH2002", "Kh2002 Service Star");
        put("BF3_ID_P_WSTAR_NAME_M320HE", "M320 Service Star");
        put("BF3_ID_P_WSTAR_NAME_M1911LIT", "M1911 Tact");
        put("BF3_ID_P_WSTAR_NAME_SAIGA", "Saiga 12k Service Star");
        put("BF3_ID_P_WSTAR_NAME_PDR", "Pdw-r Service Star");
        put("BF3_ID_P_WSTAR_NAME_CLAY", "Claymore Service Star");
        put("BF3_ID_P_WSTAR_NAME_SCARH", "Scar-h Service Star");
        put("BF3_ID_P_WSTAR_NAME_STINGER", "Fim-92 Stinger Service Star");
        put("BF3_ID_P_WSTAR_NAME_P90", "P90 Service Star");
        put("BF3_ID_P_WSTAR_NAME_TYPE88", "Type 88 Lmg Service Star");
        put("BF3_ID_P_WSTAR_NAME_MK11", "Mk11 Mod 0 Service Star");
        put("BF3_ID_P_WSTAR_NAME_RPK", "Rpk-74m Service Star");
        put("BF3_ID_P_WSTAR_NAME_M26SLUG", "M26 Slug Service Star");
        put("BF3_ID_P_WSTAR_NAME_AEK971", "Aek-971 Service Star");
        put("BF3_ID_P_WSTAR_NAME_A91", "A-91 Service Star");
        put("BF3_ID_P_WSTAR_NAME_M40A5", "M40a5 Service Star");
        put("BF3_ID_P_WSTAR_NAME_M93R", "93r Service Star");
        put("BF3_ID_P_WSTAR_NAME_M98B", "M98b Service Star");

        put("BF3_ID_P_CLASS_STAR_NAME_ASSAULT", "Assault Service Star");
        put("BF3_ID_P_CLASS_STAR_NAME_SUPPORT", "Support Service Star");
        put("BF3_ID_P_CLASS_STAR_NAME_ENGINEER", "Engineer Service Star");
        put("BF3_ID_P_CLASS_STAR_NAME_RECON", "Recon Service Star");
        put("BF3_ID_P_CLASS_STAR_NAME_MBT", "MBT Service Star");
        put("BF3_ID_P_CLASS_STAR_NAME_IFV", "Ifv Service Star");
        put("BF3_ID_P_CLASS_STAR_NAME_AA", "AA Service Star");
        put("BF3_ID_P_CLASS_STAR_NAME_SHELI", "Scout Helicopter Service Star");
        put("BF3_ID_P_CLASS_STAR_NAME_AHELI", "Attack Helicopter Service Star");
        put("BF3_ID_P_CLASS_STAR_NAME_JET", "Jet Service Star");
        put("BF3_ID_P_CLASS_STAR_NAME", "Mobile Artillery Service Star"); //TODO need IDs for these two stars
        put("BF3_ID_P_CLASS_STAR_NAME", "Tank Destroyers Service Star");
    }};

    public static String getAwardTitle(String key) {
        return AWARDS.containsKey(key) ? AWARDS.get(key) : key;
    }
}
