package com.ninetwozero.bf3droid.util;

import java.util.HashMap;
import java.util.Map;

public class Ranks {
    
    private Ranks(){}

    private static Map<String, String> RANKS = new HashMap<String, String>(){{
        put("ID_P_RANK00_NAME", "Recruit");
        put("ID_P_RANK01_NAME", "Private First Class");
        put("ID_P_RANK02_NAME", "Private First Class 1 Star");
        put("ID_P_RANK03_NAME", "Private First Class 2 Star");
        put("ID_P_RANK04_NAME", "Private First Class 3 Star");
        put("ID_P_RANK05_NAME", "Lance Corporal");
        put("ID_P_RANK06_NAME", "Lance Corporal 1 Star");
        put("ID_P_RANK07_NAME", "Lance Corporal 2 Star");
        put("ID_P_RANK08_NAME", "Lance Corporal 3 Star");
        put("ID_P_RANK09_NAME", "Corporal");
        put("ID_P_RANK10_NAME", "Corporal 1 Star");
        put("ID_P_RANK11_NAME", "Corporal 2 Star");
        put("ID_P_RANK12_NAME", "Corporal 3 Star");
        put("ID_P_RANK13_NAME", "Sergeant");
        put("ID_P_RANK14_NAME", "Sergeant 1 Star");
        put("ID_P_RANK15_NAME", "Sergeant 2 Star");
        put("ID_P_RANK16_NAME", "Sergeant 3 Star");
        put("ID_P_RANK17_NAME", "Staff Sergeant");
        put("ID_P_RANK18_NAME", "Staff Sergeant 1 Star");
        put("ID_P_RANK19_NAME", "Staff Sergeant 2 Star");
        put("ID_P_RANK20_NAME", "Gunnery Sergeant");
        put("ID_P_RANK21_NAME", "Gunnery Sergeant 1 Star");
        put("ID_P_RANK22_NAME", "Gunnery Sergeant 2 Star");
        put("ID_P_RANK23_NAME", "Master Sergeant");
        put("ID_P_RANK24_NAME", "Master Sergeant 1 Star");
        put("ID_P_RANK25_NAME", "Master Sergeant 2 Star");
        put("ID_P_RANK26_NAME", "First Sergeant");
        put("ID_P_RANK27_NAME", "First Sergeant 1 Star");
        put("ID_P_RANK28_NAME", "First Sergeant 2 Star");
        put("ID_P_RANK29_NAME", "Master Gunnery Sergeant");
        put("ID_P_RANK30_NAME", "Master Gunnery Sergeant 1 Star");
        put("ID_P_RANK31_NAME", "Master Gunnery Sergeant 2 Star");
        put("ID_P_RANK32_NAME", "Sergeant Major");
        put("ID_P_RANK33_NAME", "Sergeant Major 1 Star");
        put("ID_P_RANK34_NAME", "Sergeant Major 2 Star");
        put("ID_P_RANK35_NAME", "Warrant Officer 1 Star");
        put("ID_P_RANK36_NAME", "Chief Warrant Officer Two");
        put("ID_P_RANK37_NAME", "Chief Warrant Officer THREE");
        put("ID_P_RANK38_NAME", "Chief Warrant Officer FOUR");
        put("ID_P_RANK39_NAME", "Chief Warrant Officer FIVE");
        put("ID_P_RANK40_NAME", "Second Lieutenant");
        put("ID_P_RANK41_NAME", "First Lieutenant");
        put("ID_P_RANK42_NAME", "Captain");
        put("ID_P_RANK43_NAME", "Major");
        put("ID_P_RANK44_NAME", "Lieutenant Colonel");
        put("ID_P_RANK45_NAME", "Colonel");
        put("ID_P_RANK46_NAME", "Colonel Service Star 1");
        put("ID_P_RANK47_NAME", "Colonel Service Star 2");
        put("ID_P_RANK48_NAME", "Colonel Service Star 3");
        put("ID_P_RANK49_NAME", "Colonel Service Star 4");
        put("ID_P_RANK50_NAME", "Colonel Service Star 5");
        put("ID_P_RANK51_NAME", "Colonel Service Star 6");
        put("ID_P_RANK52_NAME", "Colonel Service Star 7");
        put("ID_P_RANK53_NAME", "Colonel Service Star 8");
        put("ID_P_RANK54_NAME", "Colonel Service Star 9");
        put("ID_P_RANK55_NAME", "Colonel Service Star 10");
        put("ID_P_RANK56_NAME", "Colonel Service Star 11");
        put("ID_P_RANK57_NAME", "Colonel Service Star 12");
        put("ID_P_RANK58_NAME", "Colonel Service Star 13");
        put("ID_P_RANK59_NAME", "Colonel Service Star 14");
        put("ID_P_RANK60_NAME", "Colonel Service Star 15");
        put("ID_P_RANK61_NAME", "Colonel Service Star 16");
        put("ID_P_RANK62_NAME", "Colonel Service Star 17");
        put("ID_P_RANK63_NAME", "Colonel Service Star 18");
        put("ID_P_RANK64_NAME", "Colonel Service Star 19");
        put("ID_P_RANK65_NAME", "Colonel Service Star 20");
        put("ID_P_RANK66_NAME", "Colonel Service Star 21");
        put("ID_P_RANK67_NAME", "Colonel Service Star 22");
        put("ID_P_RANK68_NAME", "Colonel Service Star 23");
        put("ID_P_RANK69_NAME", "Colonel Service Star 24");
        put("ID_P_RANK70_NAME", "Colonel Service Star 25");
        put("ID_P_RANK71_NAME", "Colonel Service Star 26");
        put("ID_P_RANK72_NAME", "Colonel Service Star 27");
        put("ID_P_RANK73_NAME", "Colonel Service Star 28");
        put("ID_P_RANK74_NAME", "Colonel Service Star 29");
        put("ID_P_RANK75_NAME", "Colonel Service Star 30");
        put("ID_P_RANK76_NAME", "Colonel Service Star 31");
        put("ID_P_RANK77_NAME", "Colonel Service Star 32");
        put("ID_P_RANK78_NAME", "Colonel Service Star 33");
        put("ID_P_RANK79_NAME", "Colonel Service Star 34");
        put("ID_P_RANK80_NAME", "Colonel Service Star 35");
        put("ID_P_RANK81_NAME", "Colonel Service Star 36");
        put("ID_P_RANK82_NAME", "Colonel Service Star 37");
        put("ID_P_RANK83_NAME", "Colonel Service Star 38");
        put("ID_P_RANK84_NAME", "Colonel Service Star 39");
        put("ID_P_RANK85_NAME", "Colonel Service Star 40");
        put("ID_P_RANK86_NAME", "Colonel Service Star 41");
        put("ID_P_RANK87_NAME", "Colonel Service Star 42");
        put("ID_P_RANK88_NAME", "Colonel Service Star 43");
        put("ID_P_RANK89_NAME", "Colonel Service Star 44");
        put("ID_P_RANK90_NAME", "Colonel Service Star 45");
        put("ID_P_RANK91_NAME", "Colonel Service Star 46");
        put("ID_P_RANK92_NAME", "Colonel Service Star 47");
        put("ID_P_RANK93_NAME", "Colonel Service Star 48");
        put("ID_P_RANK94_NAME", "Colonel Service Star 49");
        put("ID_P_RANK95_NAME", "Colonel Service Star 50");
        put("ID_P_RANK96_NAME", "Colonel Service Star 51");
        put("ID_P_RANK97_NAME", "Colonel Service Star 52");
        put("ID_P_RANK98_NAME", "Colonel Service Star 53");
        put("ID_P_RANK99_NAME", "Colonel Service Star 54");
        put("ID_P_RANK100_NAME", "Colonel Service Star 55");
        put("ID_P_RANK101_NAME", "Colonel Service Star 56");
        put("ID_P_RANK102_NAME", "Colonel Service Star 57");
        put("ID_P_RANK103_NAME", "Colonel Service Star 58");
        put("ID_P_RANK104_NAME", "Colonel Service Star 59");
        put("ID_P_RANK105_NAME", "Colonel Service Star 60");
        put("ID_P_RANK106_NAME", "Colonel Service Star 61");
        put("ID_P_RANK107_NAME", "Colonel Service Star 62");
        put("ID_P_RANK108_NAME", "Colonel Service Star 63");
        put("ID_P_RANK109_NAME", "Colonel Service Star 64");
        put("ID_P_RANK110_NAME", "Colonel Service Star 65");
        put("ID_P_RANK111_NAME", "Colonel Service Star 66");
        put("ID_P_RANK112_NAME", "Colonel Service Star 67");
        put("ID_P_RANK113_NAME", "Colonel Service Star 68");
        put("ID_P_RANK114_NAME", "Colonel Service Star 69");
        put("ID_P_RANK115_NAME", "Colonel Service Star 70");
        put("ID_P_RANK116_NAME", "Colonel Service Star 71");
        put("ID_P_RANK117_NAME", "Colonel Service Star 72");
        put("ID_P_RANK118_NAME", "Colonel Service Star 73");
        put("ID_P_RANK119_NAME", "Colonel Service Star 74");
        put("ID_P_RANK120_NAME", "Colonel Service Star 75");
        put("ID_P_RANK121_NAME", "Colonel Service Star 76");
        put("ID_P_RANK122_NAME", "Colonel Service Star 77");
        put("ID_P_RANK123_NAME", "Colonel Service Star 78");
        put("ID_P_RANK124_NAME", "Colonel Service Star 79");
        put("ID_P_RANK125_NAME", "Colonel Service Star 80");
        put("ID_P_RANK126_NAME", "Colonel Service Star 81");
        put("ID_P_RANK127_NAME", "Colonel Service Star 82");
        put("ID_P_RANK128_NAME", "Colonel Service Star 83");
        put("ID_P_RANK129_NAME", "Colonel Service Star 84");
        put("ID_P_RANK130_NAME", "Colonel Service Star 85");
        put("ID_P_RANK131_NAME", "Colonel Service Star 86");
        put("ID_P_RANK132_NAME", "Colonel Service Star 87");
        put("ID_P_RANK133_NAME", "Colonel Service Star 88");
        put("ID_P_RANK134_NAME", "Colonel Service Star 89");
        put("ID_P_RANK135_NAME", "Colonel Service Star 90");
        put("ID_P_RANK136_NAME", "Colonel Service Star 91");
        put("ID_P_RANK137_NAME", "Colonel Service Star 92");
        put("ID_P_RANK138_NAME", "Colonel Service Star 93");
        put("ID_P_RANK139_NAME", "Colonel Service Star 94");
        put("ID_P_RANK140_NAME", "Colonel Service Star 95");
        put("ID_P_RANK141_NAME", "Colonel Service Star 96");
        put("ID_P_RANK142_NAME", "Colonel Service Star 97");
        put("ID_P_RANK143_NAME", "Colonel Service Star 98");
        put("ID_P_RANK144_NAME", "Colonel Service Star 99");
        put("ID_P_RANK145_NAME", "Colonel Service Star 100");
    }};

    public static String getRankTitle(String key) {
        return RANKS.containsKey(key) ? RANKS.get(key) : key;
    }
}
